name: spectraBrowserEnv
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - contourpy=1.3.3=py313hf069bd2_3
  - cycler=0.12.1=pyhcf101f3_2
  - double-conversion=3.3.1=he0c23c2_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py313hd650c13_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=11.4.5=h5f2951f_0
  - icu=75.1=he0c23c2_0
  - kiwisolver=1.4.9=py313h1a38498_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.8=default_ha2db4b5_1
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libglib=2.84.3=h1c1036b_0
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libmpdec=4.0.0=h2466b09_0
  - libpng=1.6.54=h7351971_0
  - libsqlite=3.51.2=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - matplotlib=3.10.8=py313hfa70ccb_0
  - matplotlib-base=3.10.8=py313he1ded55_0
  - mkl=2025.3.0=hac47afa_455
  - munkres=1.1.4=pyhd8ed1ab_1
  - numpy=2.4.1=py313hce7ae62_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=3.0.0=py313h26f5e95_0
  - pcre2=10.45=h99c9b8b_0
  - pillow=12.1.0=py313h38f99e1_0
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h5112557_1
  - ply=3.11=pyhd8ed1ab_3
  - pthread-stubs=0.4=h0e40799_1002
  - pybaselines=1.2.1=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyqt6=6.8.1=py313hfe59770_1
  - pyqt6-sip=13.10.0=py313hfe59770_1
  - pyside6=6.8.3=py313h3e3797f_0
  - python=3.13.9=hdf00ec1_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.8.3=h02ddd7d_4
  - setuptools=80.10.1=pyh332efcf_0
  - sip=6.10.0=py313hfe59770_1
  - six=1.17.0=pyhe01879c_1
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.13=h2c6b04d_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py313h5ea7bf4_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zlib-ng=2.3.2=h0261ad2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - scipy==1.17.0
      - sif-tools==2.1.2
prefix:
